### ISSUE TITLE
Confusion matrix

### ISSUE THREAD

**Issue by natank1** [nryant/dscore#3]
For some reason when I run the  contingency_matrix and bcubed   , I always get equal precision and recall  
no matter what the inputs are.

**Comment by nryant** [comment]
Could I see example inputs where this occurs? In the meantime, let me offer the following as proof that ``bcubed`` is working:

    import numpy as np
    from scorelib.metrics import bcubed, contingency_matrix
    
    # Case 1: Perfect clustering.
    print('Case 1: Perfect clustering')
    print('----------------------------------')
    x = np.arange(10)
    y = np.arange(10) + 10
    cm = contingency_matrix(x, y)
    print('Precision: %.2f, Recall: %.2f, F1: %.2f' % bcubed(None, None, cm))
    print('Precision: %.2f, Recall: %.2f, F1: %.2f' % bcubed(x, y))
    print('')

    # Case 2: All classes collapsed.
    print('Case 2: All classes collapsed')
    print('---------------------------------------')
    y = np.zeros_like(x)
    cm = contingency_matrix(x, y)
    print('Precision: %.2f, Recall: %.2f, F1: %.2f' % bcubed(None, None, cm))
    print('Precision: %.2f, Recall: %.2f, F1: %.2f' % bcubed(x, y))


which outputs

    Case 1: Perfect clustering
    ----------------------------------
    Precision: 1.00, Recall: 1.00, F1: 1.00
    Precision: 1.00, Recall: 1.00, F1: 1.00

    Case 2: All classes collapsed
    ---------------------------------------
    Precision: 0.10, Recall: 1.00, F1: 0.18
    Precision: 0.10, Recall: 1.00, F1: 0.18
